Parameters:
  Enviroment:
    Type: String
  AWSAccount:
    Type: String

Resources:
  OrchECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub ${Enviroment}-orch-frontend-application
      RepositoryPolicyText:
        Version: "2008-10-17"
        Statement:
          - Sid: AllowPullPushForDeployerRole
            Effect: Allow
            Principal:
              AWS: !sub "arn:aws:iam::{AWSAccount}:root"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
