Parameters:
  Environment:
    Type: String
  AWSAccount:
    Type: String
  Region:
    Type: String

Resources:
  OrchECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub ${Environment}-orch-app-cluster

  OrchECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${Environment}-orch-frontend

  OrchFrontendECSExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  OrchFrontendECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${Environment}-orch-frontend-ecs-service
      Cluster: !Ref OrchECSCluster
      TaskDefinition: !Ref OrchFrontendTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - subnet-0027e271c35f828c1
            - subnet-01b7b1c835828eb3d
            - subnet-0b648700a8ac43736
          SecurityGroups:
  OrchFrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Environment}-orch-frontend-ecs-task-definition
      Cpu: 256
      Memory: 0.5GB
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt OrchFrontendECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: sandpit-orch-frontend-image
          Image: !Sub ${AWSAccount}.dkr.ecr.${Region}.amazonaws.com/sandpit-orch-frontend-image-repository:latest
          PortMappings:
            - ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref OrchECSLogGroup
              awslogs-region: !Sub ${Region}
              awslogs-stream-prefix: ecs
