name: Deploy frontend build and promote

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    uses: ./.github/workflows/deploy-frontend.yml
    needs: run-checks
    secrets:
      ARTIFACT_BUCKET_NAME: ${{ secrets.ARTIFACT_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}