name: Pre-merge checks for Terraform
on:
  pull_request:
    paths: ['configuration/terraform/**']
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get Terraform version
        id: getterraformversion
        run: echo "::set-output name=version::$(cat configuration/terraform/.terraform-version)"

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.getterraformversion.outputs.version }}

      - name: Terraform Format Check
        working-directory: configuration/terraform/
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: configuration/terraform/
        run: |
          terraform init -input=false -backend=false
          terraform validate
